// <auto-generated />
using System;
using DMI.SMS.Persistence.EntityFrameworkCore.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DMI.SMS.Persistence.EntityFrameworkCore.PostgreSQL.Migrations
{
    [DbContext(typeof(SMSDbContext))]
    partial class SMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DMI.SMS.Domain.Entities.ContactPerson", b =>
                {
                    b.Property<int>("GdbArchiveOid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GdbArchiveOid"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("GdbFromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GdbToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GlobalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastEditedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditedUser")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentGdbArchiveOid")
                        .HasColumnType("integer");

                    b.Property<string>("ParentGuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("GdbArchiveOid");

                    b.HasIndex("ParentGdbArchiveOid");

                    b.ToTable("ContactPersons");
                });

            modelBuilder.Entity("DMI.SMS.Domain.Entities.ElevationAngles", b =>
                {
                    b.Property<int>("GdbArchiveOid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GdbArchiveOid"));

                    b.Property<string>("AngleComment")
                        .HasColumnType("text");

                    b.Property<int?>("AngleIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("Angle_E")
                        .HasColumnType("integer");

                    b.Property<int?>("Angle_N")
                        .HasColumnType("integer");

                    b.Property<int?>("Angle_NE")
                        .HasColumnType("integer");

                    b.Property<int?>("Angle_NW")
                        .HasColumnType("integer");

                    b.Property<int?>("Angle_S")
                        .HasColumnType("integer");

                    b.Property<int?>("Angle_SE")
                        .HasColumnType("integer");

                    b.Property<int?>("Angle_SW")
                        .HasColumnType("integer");

                    b.Property<int?>("Angle_W")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GdbFromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GdbToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GlobalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastEditedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditedUser")
                        .HasColumnType("text");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentGdbArchiveOid")
                        .HasColumnType("integer");

                    b.Property<string>("ParentGuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.HasKey("GdbArchiveOid");

                    b.HasIndex("ParentGdbArchiveOid");

                    b.ToTable("ElevationAngles");
                });

            modelBuilder.Entity("DMI.SMS.Domain.Entities.SensorLocation", b =>
                {
                    b.Property<int>("GdbArchiveOid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GdbArchiveOid"));

                    b.Property<string>("AccessAddress")
                        .HasColumnType("text");

                    b.Property<double?>("BaroLevel")
                        .HasColumnType("double precision");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GdbFromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GdbToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GlobalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastEditedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditedUser")
                        .HasColumnType("text");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<double?>("Sl_easting")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sl_geo_lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sl_geo_long")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sl_northing")
                        .HasColumnType("double precision");

                    b.Property<int?>("Sl_utm")
                        .HasColumnType("integer");

                    b.Property<int?>("StationidDMI")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.HasKey("GdbArchiveOid");

                    b.ToTable("SensorLocations");
                });

            modelBuilder.Entity("DMI.SMS.Domain.Entities.ServiceVisitReport", b =>
                {
                    b.Property<int>("GdbArchiveOid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GdbArchiveOid"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GdbFromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GdbToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GlobalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastEditedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditedUser")
                        .HasColumnType("text");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentGdbArchiveOid")
                        .HasColumnType("integer");

                    b.Property<string>("ParentGuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.HasKey("GdbArchiveOid");

                    b.HasIndex("ParentGdbArchiveOid");

                    b.ToTable("ServiceVisitReports");
                });

            modelBuilder.Entity("DMI.SMS.Domain.Entities.StationInformation", b =>
                {
                    b.Property<int>("GdbArchiveOid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gdb_archive_oid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GdbArchiveOid"));

                    b.Property<string>("AccessAddress")
                        .HasColumnType("text")
                        .HasColumnName("accessaddress");

                    b.Property<DateTime?>("Addworkforcedate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("addworkforcedate");

                    b.Property<string>("Altstationid")
                        .HasColumnType("text")
                        .HasColumnName("altstationid");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int?>("Country")
                        .HasColumnType("integer")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("text")
                        .HasColumnName("created_user");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datefrom");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateto");

                    b.Property<string>("Facilityid")
                        .HasColumnType("text")
                        .HasColumnName("facilityid");

                    b.Property<DateTime>("GdbFromDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gdb_from_date");

                    b.Property<DateTime>("GdbToDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gdb_to_date");

                    b.Property<string>("GlobalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("globalid");

                    b.Property<double?>("Hha")
                        .HasColumnType("double precision")
                        .HasColumnName("hha");

                    b.Property<double?>("Hhp")
                        .HasColumnType("double precision")
                        .HasColumnName("hhp");

                    b.Property<DateTime?>("LastEditedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_date");

                    b.Property<string>("LastEditedUser")
                        .HasColumnType("text")
                        .HasColumnName("last_edited_user");

                    b.Property<DateTime?>("Lastservicedate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastservicedate");

                    b.Property<DateTime?>("Lastvisitdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastvisitdate");

                    b.Property<DateTime?>("Nextservicedate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nextservicedate");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("objectid");

                    b.Property<string>("Referencetomaintenanceagreement")
                        .HasColumnType("text")
                        .HasColumnName("referencetomaintenanceagreement");

                    b.Property<string>("Regionid")
                        .HasColumnType("text")
                        .HasColumnName("regionid");

                    b.Property<int?>("Serviceinterval")
                        .HasColumnType("integer")
                        .HasColumnName("serviceinterval");

                    b.Property<string>("Shape")
                        .HasColumnType("text");

                    b.Property<double?>("Si_easting")
                        .HasColumnType("double precision")
                        .HasColumnName("si_easting");

                    b.Property<double?>("Si_geo_lat")
                        .HasColumnType("double precision")
                        .HasColumnName("si_geo_lat");

                    b.Property<double?>("Si_geo_long")
                        .HasColumnType("double precision")
                        .HasColumnName("si_geo_long");

                    b.Property<double?>("Si_northing")
                        .HasColumnType("double precision")
                        .HasColumnName("si_northing");

                    b.Property<int?>("Si_utm")
                        .HasColumnType("integer")
                        .HasColumnName("si_utm");

                    b.Property<int?>("StationIDDMI")
                        .HasColumnType("integer")
                        .HasColumnName("stationid_dmi");

                    b.Property<string>("StationName")
                        .HasColumnType("text")
                        .HasColumnName("stationname");

                    b.Property<int?>("StationOwner")
                        .HasColumnType("integer")
                        .HasColumnName("stationOwner");

                    b.Property<string>("Stationid_icao")
                        .HasColumnType("text")
                        .HasColumnName("stationid_icao");

                    b.Property<int?>("Stationtype")
                        .HasColumnType("integer")
                        .HasColumnName("stationtype");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<double?>("Wgs_lat")
                        .HasColumnType("double precision")
                        .HasColumnName("wgs_lat");

                    b.Property<double?>("Wgs_long")
                        .HasColumnType("double precision")
                        .HasColumnName("wgs_long");

                    b.Property<string>("Wigosid")
                        .HasColumnType("text")
                        .HasColumnName("wigosid");

                    b.Property<string>("Wmocountrycode")
                        .HasColumnType("text")
                        .HasColumnName("wmocountrycode");

                    b.Property<int?>("Wmorbcn")
                        .HasColumnType("integer")
                        .HasColumnName("wmorbcn");

                    b.Property<int?>("Wmorbsn")
                        .HasColumnType("integer")
                        .HasColumnName("wmorbsn");

                    b.Property<int?>("Wmorbsnradio")
                        .HasColumnType("integer")
                        .HasColumnName("wmorbsnradio");

                    b.Property<string>("Wmostationid")
                        .HasColumnType("text")
                        .HasColumnName("wmostationid");

                    b.HasKey("GdbArchiveOid");

                    b.ToTable("StationInformations");
                });

            modelBuilder.Entity("DMI.SMS.Domain.Entities.ContactPerson", b =>
                {
                    b.HasOne("DMI.SMS.Domain.Entities.StationInformation", "StationInformation")
                        .WithMany("ContactPersons")
                        .HasForeignKey("ParentGdbArchiveOid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StationInformation");
                });

            modelBuilder.Entity("DMI.SMS.Domain.Entities.ElevationAngles", b =>
                {
                    b.HasOne("DMI.SMS.Domain.Entities.SensorLocation", "SensorLocation")
                        .WithMany()
                        .HasForeignKey("ParentGdbArchiveOid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SensorLocation");
                });

            modelBuilder.Entity("DMI.SMS.Domain.Entities.ServiceVisitReport", b =>
                {
                    b.HasOne("DMI.SMS.Domain.Entities.StationInformation", "StationInformation")
                        .WithMany()
                        .HasForeignKey("ParentGdbArchiveOid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("StationInformation");
                });

            modelBuilder.Entity("DMI.SMS.Domain.Entities.StationInformation", b =>
                {
                    b.Navigation("ContactPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
